package com.samuelribeiro.recorda.domain.model

/**
 * A single question/answer pair generated by the LLM for a study topic.
 *
 * @property question The prompt the user is expected to recall.
 * @property answer The expected answer, used to grade active-recall practice.
 */
data class Flashcard(
    val question: String,
    val answer: String,
)
