package com.samuelribeiro.recorda.data.mapper

import com.samuelribeiro.recorda.domain.model.Flashcard
import javax.inject.Inject

/**
 * Parses the raw text generated by the LLM into [Flashcard]s.
 *
 * Expects one flashcard per line in the format `P: <question> | R: <answer>` — the format
 * requested in the prompt built by [com.samuelribeiro.recorda.data.repository.TopicRepositoryImpl].
 * Lines that don't match are silently skipped, so minor formatting drift from the LLM
 * degrades gracefully instead of failing the whole generation.
 */
class FlashcardMapper @Inject constructor() {

    fun toFlashcards(rawText: String): List<Flashcard> =
        rawText.lineSequence()
            .mapNotNull(::parseLine)
            .toList()

    private fun parseLine(line: String): Flashcard? {
        val separatorIndex = line.indexOf('|')
        if (separatorIndex == -1) return null

        val question = line.substring(0, separatorIndex).substringAfter(':').trim()
        val answer = line.substring(separatorIndex + 1).substringAfter(':').trim()

        return if (question.isNotBlank() && answer.isNotBlank()) Flashcard(question, answer) else null
    }
}
