package com.samuelribeiro.recorda.data.mapper

import com.samuelribeiro.recorda.domain.model.MindMapNode
import javax.inject.Inject

/**
 * Parses the raw text generated by the LLM into a [MindMapNode] tree.
 *
 * Expects one node per line, indented by 2 spaces per level and prefixed with `-` — the format
 * requested in the prompt built by [com.samuelribeiro.recorda.data.prompt.GeminiMindMapPromptBuilder].
 * The first line becomes the root, regardless of its indentation. Indentation jumps and missing
 * prefixes degrade gracefully instead of failing the whole generation.
 */
class MindMapMapper @Inject constructor() {

    /** Converts the raw LLM response into a [MindMapNode] tree rooted at [topicName]. */
    fun toMindMap(topicName: String, rawText: String): MindMapNode {
        val lines = rawText.lineSequence()
            .filter { it.isNotBlank() }
            .map(::parseLine)
            .toList()

        if (lines.isEmpty()) return MindMapNode(id = "0", title = topicName)

        val root = MutableNode(lines.first().second.ifBlank { topicName })
        val stack = ArrayDeque<Pair<Int, MutableNode>>()
        stack.addLast(0 to root)

        for ((depth, title) in lines.drop(1)) {
            while (stack.size > 1 && stack.last().first >= depth) stack.removeLast()
            val child = MutableNode(title)
            stack.last().second.children += child
            stack.addLast(depth to child)
        }

        return root.toImmutable("0")
    }

    private fun parseLine(line: String): Pair<Int, String> {
        val depth = line.takeWhile { it == ' ' }.length / 2
        val title = line.trim().removePrefix("-").trim()
        return depth to title
    }

    private class MutableNode(val title: String, val children: MutableList<MutableNode> = mutableListOf())

    private fun MutableNode.toImmutable(path: String): MindMapNode = MindMapNode(
        id = path,
        title = title,
        children = children.mapIndexed { index, child -> child.toImmutable("$path-$index") },
    )
}
