package com.samuelribeiro.recorda.data.mapper

import com.samuelribeiro.recorda.domain.model.OralAnswerEvaluation
import com.samuelribeiro.recorda.domain.model.OralAnswerVerdict
import javax.inject.Inject

/**
 * Parses the raw text generated by the LLM into an [OralAnswerEvaluation].
 *
 * Expects the format `VEREDITO: <CORRECT|PARTIAL|INCORRECT> | FEEDBACK: <feedback>` — the
 * format requested in the prompt built by [com.samuelribeiro.recorda.data.prompt.GeminiOralAnswerPromptBuilder].
 * If the verdict is missing or unrecognized, defaults to [OralAnswerVerdict.PARTIAL] and falls
 * back to the raw text as feedback, so minor formatting drift from the LLM degrades gracefully.
 */
class OralAnswerMapper @Inject constructor() {

    /** Converts the raw LLM response into an [OralAnswerEvaluation]. */
    fun toEvaluation(rawText: String): OralAnswerEvaluation {
        val line = rawText.lineSequence().firstOrNull { it.contains("VEREDITO") } ?: rawText

        val verdictText = line.substringAfter("VEREDITO:", "")
            .substringBefore('|')
            .trim()
            .uppercase()
        val feedback = line.substringAfter("FEEDBACK:", "").trim()

        val verdict = OralAnswerVerdict.entries.find { it.name == verdictText } ?: OralAnswerVerdict.PARTIAL

        return OralAnswerEvaluation(
            verdict = verdict,
            feedback = feedback.ifBlank { rawText.trim() },
        )
    }
}
